export const UPDATE_CALCULATIONS = 'UPDATE_CALCULATIONS';
export const UPDATE_INVOICES_LIST = 'UPDATE_INVOICES_LIST';
export const UPDATE_WITHDRAWALS_LIST = 'UPDATE_WITHDRAWALS_LIST';
export const UPDATE_PAYMENTS_LIST = 'UPDATE_PAYMENTS_LIST';
export const DEBOUNCED_RATE_REFRESH = 'DEBOUNCED_RATE_REFRESH';
export const IS_REFRESHING = 'IS_REFRESHING';
export const CALCULATE = 'CALCULATE';